---

downloads: ~/.ansible-downloads/

# Dotfiles
configure_dotfiles: true
dotfiles_repo: git@github.com:glennbrown/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/dotfiles
dotfiles_files:
  - .zshrc
  - .inputrc
  - .macos_defaults
  - .vimrc
  - .bashrc
  - .bash_profile

configure_terminal: false

configure_macos: true
macos_services:
  - Dock
  - Finder
  - SystemUIServer
macos_default_script: "~/.macos_defaults --no-restart"
macos_default_settings: []
# Expand save panel by default
#  - domain: NSGlobalDomain
#    key: NSNavPanelExpandedStateForSaveMode
#    type: bool
#    value: true

## Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  # Ansible installed/managed via pipx
  - bash
  - bash-completion@2
  - btop
  - brew-cask-completion
  - coreutils
  - ffmpeg
  - flac
  - gawk
  - gnu-tar
  - go
  - htop
  - iperf3
  - jq
  - just
  - lame
  - lesspipe
  - lz4
  - lzo
  - nano
  - nanorc
  - ncurses
  - neofetch
  - nmap
  - perl
  - pv
  - qemu
  - ruby
  - screenresolution
  - smartmontools
  - snappy
  - socat
  - svt-av1
  - tmux
  - webp
  - wget
  - when
  - x264
  - x265
  - xvid
  - xz

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/command-not-found
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - balenaetcher
  - coconutbattery
  - discord
  - docker
  - font-hack-nerd-font
  - font-meslo-lg-nerd-font
  - google-chrome
  - handbrake
  - iterm2
  - jellyfin-media-player
  - logi-options-plus
  - mediahuman-audio-converter
  - mediainfo
  - meld
  - musicbrainz-picard
  - netspot
  - obsidian
  - parsec
  - plex
  - powershell
  - raspberry-pi-imager
  - spotify 
  - timemachineeditor
  - utm
  - visual-studio-code
  - vlc
  - vmware-horizon-client
  - xquartz
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
