---

- name: Configure host
  hosts: all

  vars_files:
    - 'defaults.yml'

  pre_tasks:
    - name: Include other variables
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/*.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']