---

roles:
  - src: elliotweiser.osx-command-line-tools
  - src: geerlingguy.dotfiles

collections:
  - source: https://github.com/glennbrown/ansible-collection-mac.git
    name: geerlingguy.mac
    version: gb-updates
    type: git
  