---

- name: Install Pip packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    virtualenv_command: "{{ item.virtualenv_command | default(omit) }}"
    virtualenv_site_packages: "{{ item.virtualenv_site_packages | default(omit) }}"
    extra_args: "{{ item.extra_args | default('--user') }}"
  environment: 
    CFLAGS: '-I/opt/homebrew/include -L/opt/homebrew/lib'
  loop: "{{ pip_packages }}"
