---

- name: Ensure pipx is installed
  pip:
    name: pipx
    state: present

- name: Install Pip packages via pipx
  community.general.pipx:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(present) }}"
    system_site_packages: "{{ item.system_site_packages | default(true) }}"
    install_apps: "{{ item.install_apps | default(true) }}"
    inject_packages: "{{ item.inject_packages | default(omit) }}"
    install_deps: "{{ item.install_deps | default(true) }}"
  loop: "{{ pipx_packages }}"