---

homebrew_user: gbrown
homebrew_group: admin

configure_dock: true

dockitems_remove:
  - TV
  - 'App Store'
  - 'System Settings'

dockitems_persist:
  - name: Launchpad
    path: "/System/Applications/Launchpad.app/"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app/"
    pos: 2
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: Messages
    path: "/System/Applications/Messages.app/"
    pos: 4
  - name: Mail
    path: "/System/Applications/Mail.app/"
    pos: 5
  - name: Fantastical
    path: "/Applications/Fantastical.app/"
    pos: 6
  - name: Notes
    path: "/System/Applications/Notes.app/"
    pos: 7
  - name: Photos
    path: "/System/Applications/Photos.app/"
    pos: 8
  - name: iTerm
    path: "/Applications/iTerm.app/"
    pos: 9
  - name: 1Password
    path: "/Applications/1Password.app/"
    pos: 10
  - name: Ivory
    path: "/Applications/Ivory.app/"
    pos: 11
  - name: Discord
    path: "/Applications/Discord.app/"
    pos: 12
  - name: IRCCloud
    path: "/Users/gbrown/Applications/IRCCloud.app/"
    pos: 13
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 14
  - name: "Shortcuts"
    path: "/System/Applications/Shortcuts.app/"
    pos: 15

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/command-not-found
  - homebrew/services

homebrew_installed_packages:
  # Ansible install/managed via pipx
  - bash
  - bash-completion@2
  - btop
  - brew-cask-completion
  - coreutils
  - ffmpeg
  - flac
  - gawk
  - gnu-tar
  - go
  - htop
  - iperf3
  - jq
  - just
  - lame
  - lesspipe
  - lz4
  - lzo
  - nano
  - nanorc
  - ncurses
  - neofetch
  - nmap
  - perl
  - pv
  - qemu
  - ruby
  - screenresolution
  - smartmontools
  - snappy
  - socat
  - sshpass
  - svt-av1
  - tmux
  - webp
  - wget
  - when
  - x264
  - x265
  - xvid
  - xz

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - balenaetcher
  - coconutbattery
  - docker
  - font-hack-nerd-font
  - font-meslo-lg-nerd-font
  - handbrake
  - jellyfin-media-player
  - logi-options-plus
  - mediahuman-audio-converter
  - mediainfo
  - meld
  - musicbrainz-picard
  - netspot
  - obsidian
  - parsec
  - plex
  - plexamp
  - raspberry-pi-imager
  - spotify 
  - timemachineeditor
  - utm
  - visual-studio-code
  - vlc
  - vmware-horizon-client
  - xquartz

mas_installed_apps:
  # Tools
  - { id: 1474335294, name: "GoodLinks" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1611378436, name: "Pure Paste" }
  - { id: 1474276998, name: "HP Smart" }
  - { id: 1452453066, name: "Hidden Bar" }
  - { id: 430255202, name: Mactracker }

  # iWork Stuff
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  
  # Productivity
  - { id: 975937182, name: "Fantastical" }

  # MS Office
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 462062816, name: "Microsoft PowerPoint" }
  
  # Safari Extensions
  - { id: 1569813296, name: "1Password for Safari" }
  - { id: 1320666476, name: "Wipr" }
  - { id: 510109287, name: "Short Menu" }

  # Media/Home
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1568924476, name: "Mela" }
  - { id: 1469995354, name: "Broadcasts" }
  - { id: 6444602274, name: "Ivory" }
  - { id: 1136220934, name: "Infuse" }
  
  # Dev Tools
  - { id: 497799835, name: "Xcode" }
  - { id: 404009241, name: "BBEdit" }

pipx_packages:
  - name: diceware
    state: present
  - name: speedtest-cli
    state: present
  - name: yt-dlp
    state: present